module.exports = {
  COOKIE_PARSER_SECRET: process.env.COOKIE_PARSER_SECRET,
  CSRF_CSRF_SECRET: process.env.CSRF_CSRF_SECRET,
  MONGO_URL: process.env.MONGO_URL,
  MONGO_URL_MONGOOSE: process.env.MONGO_URL_MONGOOSE,
  MYSQL_PASSWORD: process.env.MYSQL_PASSWORD,
  SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
  STRIPE_SECURE_KEY: process.env.STRIPE_SECURE_KEY,
  EMAIL_FROM: process.env.EMAIL_FROM
};
